#!/usr/bin/env bash

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)

"${SCRIPTS_DIR}/lint" || exit 1

BASE_DIR=$(dirname "${SCRIPTS_DIR}")
BABEL=${BASE_DIR}/node_modules/.bin/babel

(cd "${BASE_DIR}"; "${BABEL}" src -d lib) || exit 1
